submap=CONFIG/WALLPAPER
source = ~/.config/hypr/keymaps/submap-base.conf
bind=,escape,submap,reset

bind=,l,exec,~/.config/hypr/bin/next-wallpaper.sh; hyprctl notify 1 4000 0 ' Random wallpaper '

    

    # Set the wallpaper using Hyprland's command
    
bind=,r,exec,killall hyprpaper; hyprpaper& hyprctl notify 1 4000 0 ' Restarted hyprpaper '

