submap=CONFIG/WALLPAPER
source = ~/.config/hypr/keymaps/submap-base.conf
bind=,escape,submap,reset

bind=,l,exec,wpaperctl next; hyprctl notify 1 4000 0 ' Next wallpaper '
bind=,h,exec,wpaperctl previous; hyprctl notify 1 4000 0 ' Previous wallpaper '

bind=,r,exec,killall wpaperd; wpaperd -d; hyprctl notify 1 4000 0 ' Restarted wpaperd '

