submap=CONFIG/WAYBAR

source = ~/.config/hypr/keymaps/submap-base.conf
bind=,escape,submap,reset

bind=,r,exec,bash -c "killall -SIGUSR2 waybar; hyprctl notify 1 4000 0 ' Reloading waybar... '"
bind=,c,exec,bash -c "killall -SIGUSR1 waybar; hyprctl notify 1 4000 0 ' Toggled waybar visibility... '"
