
# Parent config keymap
submap=CONFIG
source = ~/.config/hypr/keymaps/submap-base.conf
bind=,escape,submap,reset


# Config keymap shortcuts
bind=,w,submap,CONFIG/WALLPAPER
bind=,b,submap,CONFIG/WAYBAR


# Config keymaps
source=~/dotfiles/.config/hypr/keymaps/config/wallpaper.conf
source=~/dotfiles/.config/hypr/keymaps/config/waybar.conf
