# --- Status Bar General Settings ---
set-option -g status on
set-option -g status-interval 1
set-option -g status-justify absolute-centre
set-option -g status-position top
set-option -g status-style bg=default,fg=default

# nvim -> Blue (#89B4FB)
# zsh  -> Red (#F7768E)
# tio  -> Yellow (#e0af68)
# else -> Green (#B9F27C)

_accent="#{?#{==:#{pane_current_command},nvim},##F7768E,\
#{?#{==:#{pane_current_command},zsh},##bb9af7,\
#{?#{==:#{pane_current_command},tio},##e0af68,\
#B9F27C}}}"

set -g @main_bg "#292e42"

# --- STATUS BAR CONSTRUCTION ---

# Left Side: TMUX Label + Session
# Uses #{@main_accent} for the first block background
# Uses #{@main_bg} for the second block background
set-option -g status-left-length 100
set-option -g status-left "#[bg=${_accent},fg=#16161e,bold] TMUX #[bg=#{@main_bg},fg=${_accent},nobold] #S "

# Center: Window List
# Active Window uses #{@main_accent} for background
set-window-option -g window-status-current-format "#[bg=${_accent},fg=#16161e,bold] #I:#W "
# Inactive Window uses standard text
set-window-option -g window-status-format "#[bg=default,fg=#a9b1d6] #I:#W "

# Right Side: Time + Load + User
set-option -g status-right-length 140
set-option -g status-right "#[bg=default,fg=#a9b1d6] %H:%M #[bg=#{@main_bg},fg=${_accent}] #(cut -d ' ' -f 1-3 /proc/loadavg) #[bg=${_accent},fg=#16161e,bold] #(whoami)@#H "

# --- Pane Borders ---
set -g pane-border-style fg=default
set -g pane-active-border-style fg=default
