# Keymaps
unbind C-b
set-option -g prefix M-a
bind-key M-a send-prefix

bind-key -T root M-space run '~/bin/tmux-sessionizer/find-session 2> /dev/null'
bind-key -T root F12 run 'CONFIG_FILE_NAME="tmux-sessionizer-dir.conf" ~/bin/tmux-sessionizer/tmux-sessionizer 2> /dev/null'
bind-key -T root M-enter run 'CONFIG_FILE_NAME="tmux-sessionizer-dir.conf" ~/bin/tmux-sessionizer/tmux-sessionizer 2> /dev/null'
bind-key -T root F11 run 'CONFIG_FILE_NAME="tmux-sessionizer-source.conf" ~/bin/tmux-sessionizer/tmux-sessionizer 2> /dev/null'
bind-key -T root M-\\ run '~/bin/tmux-git-finder/tmux-git-finder'
bind-key -T root M-n run '~/bin/tmux-nix-finder/tmux-nix-finder'
bind-key -T root M-/ run 'CONFIG_FILE_NAME="tmux-sessionizer-global.conf" ~/bin/tmux-sessionizer/tmux-sessionizer 2> /dev/null'
bind-key -T root M-r run '~/bin/tmux-git-cloner/tmux-git-cloner'
bind-key -T root M-s run '~/bin/tmux-sessionizer/open-ssh 2> /dev/null'

# Switch to windows using Alt + number
bind -n M-1 select-window -t 0
bind -n M-2 select-window -t 1
bind -n M-3 select-window -t 2
bind -n M-4 select-window -t 3
bind -n M-5 select-window -t 4
bind -n M-6 select-window -t 5
bind -n M-7 select-window -t 6
bind -n M-8 select-window -t 7
bind -n M-9 select-window -t 8
bind -n M-0 select-window -t 9

# Switch between sessions
bind -n M-h switch-client -p   # Alt+H: Previous session
bind -n M-l switch-client -n   # Alt+L: Next session

# Switch between windows
bind -n M-j next-window        # Alt+J: Next window
bind -n M-k previous-window    # Alt+K: Previous window
bind -n M-t new-window

# scrolling
set -g mouse on

bind -n M-u if -F "#{pane_in_mode}" \
  "send-keys -X halfpage-up" \
  "copy-mode -e; send-keys -X halfpage-up"

bind -n M-d if -F "#{pane_in_mode}" \
  "send-keys -X halfpage-down" \
  "copy-mode -e; send-keys -X halfpage-down"

# disable automatic renaming
# set-option -g allow-rename off

# Disable exit on window exit
set-option -g detach-on-destroy off

# Status bar theme
set-option -g status-style fg=white,bg=default


set-option -g status on
set-option -g status-interval 1
set-option -g status-justify left
set-option -g status-keys vi
set-option -g status-position bottom
set-option -g status-style fg=colour136,bg=default
set-option -g status-left-length 140
set-option -g status-left-style default
set-option -g status-left "TMUX: #S:#W"
set-option -g status-right-length 140
set-option -g status-right-style default
set-option -g status-right "#[fg=white,bold] #(whoami)@#H (Kernel: #(uname -r)) #[default]"
set-window-option -g window-status-style fg=#89B4FB,bg=default
set-window-option -g window-status-current-style fg=#89B4FB,bg=default
set -g window-status-format ''
set -g window-status-current-format ""
