# Keymaps
unbind C-b
set-option -g prefix M-a
bind-key M-a send-prefix

bind-key -T root M-space run '~/bin/tmux-sessionizer/find-session 2> /dev/null'
bind-key -T root F12 run 'CONFIG_FILE_NAME="tmux-sessionizer-dir.conf" ~/bin/tmux-sessionizer/tmux-sessionizer 2> /dev/null'
bind-key -T root M-enter run 'CONFIG_FILE_NAME="tmux-sessionizer-dir.conf" ~/bin/tmux-sessionizer/tmux-sessionizer 2> /dev/null'
bind-key -T root F11 run 'CONFIG_FILE_NAME="tmux-sessionizer-source.conf" ~/bin/tmux-sessionizer/tmux-sessionizer 2> /dev/null'
bind-key -T root M-\\ run '~/bin/tmux-git-finder/tmux-git-finder'
bind-key -T root M-n run '~/bin/tmux-nix-finder/tmux-nix-finder'
bind-key -T root M-/ run 'CONFIG_FILE_NAME="tmux-sessionizer-global.conf" ~/bin/tmux-sessionizer/tmux-sessionizer 2> /dev/null'
bind-key -T root M-r run '~/bin/tmux-git-cloner/tmux-git-cloner'
bind-key -T root M-s run '~/bin/tmux-sessionizer/open-ssh 2> /dev/null'
bind-key -T root M-\; run 'tmux display-popup -h 5 -T " [Create Scratchpad] " -E "~/bin/tmux-scratchpad/tmux-scratchpad"'
bind-key -T root M-o run '~/bin/tmux-kube-context/tmux-kube-context'

# Switch to windows using Alt + number
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10

# Switch between sessions
bind -n M-k switch-client -p   # Alt+H: Previous session
bind -n M-j switch-client -n   # Alt+L: Next session

# Switch between windows
bind -n M-l next-window        # Alt+J: Next window
bind -n M-h previous-window    # Alt+K: Previous window
bind -n M-t new-window

# scrolling
set -g mouse on

# Base index
set -g base-index 1
setw -g pane-base-index 1

bind -n M-u if -F "#{pane_in_mode}" \
  "send-keys -X halfpage-up" \
  "copy-mode -e; send-keys -X halfpage-up"

bind -n M-d if -F "#{pane_in_mode}" \
  "send-keys -X halfpage-down" \
  "copy-mode -e; send-keys -X halfpage-down"

# disable automatic renaming
# set-option -g allow-rename off

# Disable exit on window exit
set-option -g detach-on-destroy off

# Status bar theme
set-option -g status-style fg=white,bg=default


source-file ~/.config/tmux/theme.conf

