exec-once=[workspace special:magic silent] kitty
workspace = special:magic, on-created-empty:kitty
workspace = 1, on-created-empty:firefox 
workspace = 1, defaultName:1: Web 
workspace = 2, on-created-empty:firefox https://discord.com/channels/@me https://web.whatsapp.com https://mail.google.com
workspace = 2, defaultName:2: Comms 
workspace = 3, on-created-empty:firefox https://calendar.google.com https://tasks.google.com https://contacts.google.com
workspace = 3, defaultName:3: Mission Control 
workspace = 4, on-created-empty:kitty /usr/bin/zsh -c "/usr/bin/zsh -c \"tmux a || tmux new-session -s home \""
workspace = 4, defaultName:4: Tmux 
workspace = 5, on-created-empty:firefox https://github.com https://gitea.lightjack.de
workspace = 5, defaultName:5: GitWeb
