exec-once=[workspace 1 silent] firefox 
exec-once=[workspace 2 silent] kitty
exec-once=[workspace 3 silent] kitty
exec-once=[workspace special:magic silent] kitty
workspace = special:magic, on-created-empty:kitty
