-- Telescope
local tb = require("telescope.builtin")
vim.keymap.set("n", "<leader><leader>", tb.find_files)
vim.keymap.set("n", "<leader>ff", tb.find_files)
vim.keymap.set("n", "<leader>fg", tb.live_grep)
vim.keymap.set("n", "<leader>fs", tb.current_buffer_fuzzy_find)
vim.keymap.set("n", "<leader>fb", tb.buffers)
vim.keymap.set("n", "<leader>fh", tb.help_tags)
vim.keymap.set("n", "<leader>fq", tb.quickfix)
vim.keymap.set("n", "<leader>fl", tb.oldfiles)
vim.keymap.set({ "n", "v" }, "<leader>fc", tb.commands)
vim.keymap.set("n", "<leader>gc", tb.git_commits)
vim.keymap.set("n", "<leader>gb", tb.git_branches)
vim.keymap.set("n", "<leader>gs", tb.git_status)
